services:
  init-fileserver:
    image: alpine
    command: >
      sh -c "
        mkdir -p /data/file-server/firmware &&
        chmod -R 777 /data/file-server
      "
    volumes:
      - /data/file-server:/data/file-server
    restart: "no"

  file-server:
    image: nginx:alpine
    container_name: file-server
    depends_on:
      - init-fileserver
    ports:
      - "${HTTP_PORT}:8080"
    env_file: .env
    volumes:
      - ./nginx/firmware.conf:/etc/nginx/conf.d/firmware.conf:ro
      - ./nginx/htpasswd:/etc/nginx/.htpasswd:ro

      # agora o volume existe com permissão
      - /data/file-server/firmware:/usr/share/nginx/html/firmware

    command: >
      sh -c "
        mkdir -p /usr/share/nginx/html/firmware &&
        chown -R nginx:nginx /usr/share/nginx/html/firmware &&
        nginx -g 'daemon off;'
      "
    restart: unless-stopped
