server {
  listen 8080;
  server_name _;

  client_max_body_size 512m;

  location ^~ /firmware/ {
    alias /usr/share/nginx/html/firmware/;
    autoindex on;

    dav_methods PUT DELETE MKCOL;
    create_full_put_path on;
    dav_access user:rw group:rw all:r;

    # Exige Basic Auth só para métodos que alteram
    limit_except GET HEAD OPTIONS {
      auth_basic "restricted";
      auth_basic_user_file /etc/nginx/.htpasswd;
    }
  }
}
